# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeDay2' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # Pods for CodeDay2
  pod 'MZFormSheetPresentationController'
  pod 'AFNetworking'
  pod 'pop', '~> 1.0'
  pod 'FSLineChart'
  pod 'ChameleonFramework'
  pod ‘DFContinuousForceTouchGestureRecognizer’, '~> 0.1.0’
  pod 'SVProgressHUD'
  pod 'DTMHeatmap'

source 'https://github.com/CocoaPods/Specs.git'


pod 'AWSCognito'
pod 'AWSCognitoIdentityProvider'
pod 'AWSLex'

end

target 'CaveatWidget' do
    pod 'DTMHeatmap'
    pod 'AFNetworking'

end
